/**
 * Hand-written "key points" for a curated subset of articles (currently the
 * three guide curricula in guides.ts) — a quick-reference distillation of
 * each article's actual argument, meant to be skimmed before a conversation
 * rather than requiring a full reread. Keyed by `${tradition}/${category}/${slug}`.
 */
export const KEY_POINTS: Record<string, string[]> = {
  "islam/answers-to-common-questions/isnt-muhammad-that-prophet-awaited-by-the-jews": [
    "Muslims cite John 1:19-25 to argue the Jews expected a separate 'Prophet like Moses' distinct from the Christ, implying that Prophet is Muhammad.",
    "But if the Jews were right that the Prophet and Christ were separate, they'd also be right that the Prophet must be an Israelite — which Muhammad, an Ishmaelite, was not.",
    "The NT (John 1:45, 5:45-47; Luke 24:25-27, 44-45; Acts 10:43, 26:22-23) explicitly identifies Jesus as the one Moses and the prophets wrote of.",
    "A parallel Muslim argument (that the Prophet/Christ couldn't come from Galilee, per John 7:40-43, 50-52) proves too much — it would disprove Jesus as Christ too, which even Muslims affirm.",
    "Isaiah 9:1-2,6-7 and Micah 5:2 show the OT expected the Messiah to be tied to Bethlehem AND shine in Galilee, resolving the Jews' confusion; the NT shows Jesus fulfilling both.",
  ],
  "islam/theological-issues/more-merciful-than-the-most-merciful": [
    "The Quran calls Allah 'the Most Merciful of those who show mercy' (7:151, 12:64) and Muhammad 'a mercy for all creatures' (21:107).",
    "A lengthy hadith (Bukhari, Muslim) recounts Allah initially imposing 50 daily prayers on Muslims; Moses, meeting Muhammad on his ascent through the heavens, repeatedly told him to go back and ask for a reduction.",
    "Through Moses' persistent intercession the number was whittled down to 5 (credited as 50 in reward) — Muhammad himself stopped asking, feeling 'ashamed' before Allah.",
    "The article's point: it was Moses' compassion, not Allah's or Muhammad's initiative, that spared the Muslim community the burden — making Moses, by the hadith's own logic, more merciful than 'the Most Merciful.'",
    "Useful rhetorical move for discussion: use a tradition's own sources to expose an internal inconsistency in its central claims.",
  ],
  "islam/quranic-issues/the-gods-of-islam-unveiled": [
    "Surah 19:34-36 has Allah as narrator describing Jesus, then immediately saying 'Allah is my Lord and your Lord, so worship Him' — grammatically making Allah call Allah his own Lord.",
    "Some Muslims claim v.36 is actually a continuation of Jesus's speech (ending at v.33), but nothing in the text signals a shift back to quoting Jesus at v.34-36.",
    "Many English translations (Asad, Sarwar, Ahmed Ali, Sher Ali, Khalifa) silently insert bracketed words like '[Jesus said]' to paper over the ambiguity — revealing translators recognized the problem.",
    "Argument fits a broader pattern (also 'many gods/lords' passages elsewhere) used to challenge claims of the Quran's perfect linguistic/theological coherence.",
    "Good example of a 'grammar of the text itself' argument — worth having ready since it doesn't require external evidence, just close reading of the Arabic structure.",
  ],
  "islam/analysis-of-muhammad/how-will-a-muslim-be-saved-according-to-the-hadiths": [
    "Multiple Sahih hadiths describe Muslims being saved from Hell by having their sins swapped onto Jews and Christians, who are thrown into Hell in their place as a 'ransom' or 'sacrifice.'",
    "The hadiths are internally inconsistent about scope: some say only a subset of especially sinful Muslims benefit (Abu Musa/Mustadrak version), others say literally 'every Muslim' gets a Jew or Christian substitute (Sahih Muslim 6665-6666).",
    "A separate contradictory tradition says Muslims are purified by mutual retaliation on a bridge between Hell and Paradise, with no substitution at all.",
    "Yet another says ransom happens via pilgrimage rites on the Day of 'Arafah.",
    "Point for engagement: hadith literature offers multiple, mutually exclusive soteriologies for how a Muslim is 'saved' — useful contrast with the NT's single, consistent gospel.",
  ],
  "islam/hadith-analysis/islamic-science-fiction-the-thunder-and-the-moon": [
    "Quran 13:13 says thunder 'glorifies' Allah; major tafsirs (Ibn Abbas, the two Jalals, al-Qurtubi, al-Tirmidhi via Ibn Abbas) explain this literally: thunder is an angel who drives the clouds and hurls fire (lightning) at people God wants punished.",
    "Science: thunder is just the acoustic byproduct of lightning heating air to ~30,000°C — it doesn't drive clouds (wind does) and has no causal power at all.",
    "Quran 36:39-40 says the moon 'swims' through 27-28 fixed 'mansions/stations' in an assigned orbital course.",
    "Actual astronomy: the moon doesn't rest at stations in a traversal but continuously orbits the earth roughly every 29.5 days.",
    "Argument type: use classical, mainstream (not fringe) Islamic commentary to show the Quran's claims were understood literally by its own interpreters and fail against modern science — useful for the 'scientific miracles of the Quran' apologetic Muslims often raise.",
  ],
  "islam/turning-the-tables/turning-the-tables-pt-1a": [
    "Series concept: take verses/arguments Muslims use against Christian doctrine and show they backfire against Islam instead.",
    "Case in point: Jamal Badawi argues Jesus can't be God because Jesus prayed ('one who prays cannot be divine').",
    "Response: Jesus's prayers (Mark 14:32-36) address God as 'Abba, Father' — and Jesus taught his followers to do the same (Matt 6:9-15).",
    "But the Quran explicitly denies Jesus is God's Son and denies Allah is 'father' to anyone (9:30, 5:18) — so if Badawi's own logic (praying disproves divinity) is applied consistently, it exposes a deeper Quranic denial of the Father-Son relationship central to Christian faith, not just Jesus's deity.",
    "Rhetorical technique worth internalizing: don't just rebut the objection — show the objector's own principle, applied consistently, damages their own position.",
  ],
  "islam/polemical-issues/sunni-islams-real-shahadah": [
    "Mainstream Sunni Shahadah has two clauses: 'no god but Allah' AND 'Muhammad is the messenger of Allah.'",
    "A minority reformist Muslim movement (citing Submission.org-style sources) argues the Quran's 'real' shahada is only Q. 3:18 — a bare declaration of God's unity — and that adding Muhammad's name is itself idolatry/shirk.",
    "This internal Muslim dispute claims mainstream Sunni practice (reciting the twofold creed) has no direct Quranic textual basis and constitutes a corruption of the faith's core confession.",
    "Useful point when discussing Islam: even Islam's most foundational, universally-assumed practice (the Shahadah as recited) is contested from within by a Quran-only reform movement — the religion's own core statement of faith isn't as textually settled as commonly presented.",
    "Doesn't require a Christian counter-argument — mainly documents an intra-Islamic fault line worth knowing about when discussing 'what Muslims believe.'",
  ],
  "islam/general-issues/muhammad-as-al-amin-the-trustworthy": [
    "Muslim apologists argue Muhammad's honesty is proven because he was nicknamed 'Al-Amin' (the Trustworthy) even by enemies before his prophetic claim, citing hadiths like Abu Sufyan's testimony to Heraclius.",
    "Problem: all such hadiths were recorded by Muslims, long after Muhammad's death — there are no contemporary non-Muslim records confirming this reputation.",
    "The Quran itself records unbelievers calling Muhammad a liar, forger, and madman (majnoon) — S. 6:33, 10:41, 15:6, 16:101, 25:4-6, 35:4 — directly undercutting the 'even his enemies praised his honesty' claim.",
    "Muslims can't consistently invoke unbelievers' testimony to prove Muhammad's honesty while dismissing unbelievers' testimony that calls him a liar — a special-pleading double standard.",
    "Hadiths themselves record Muhammad approving deception for strategic ends (the assassination of Ka'b bin al-Ashraf via a staged lie, Bukhari 5:59:369) — undermining the 'impeccable, never lied' claim on its own terms.",
  ],
  "christian-theology/answers-to-common-questions/is-the-savior-necessarily-god": [
    "Objection: OT figures like Othniel and unnamed 'saviors' (Judges 3:9, Obadiah 1:21) are called 'savior' without being divine, so Jesus being called Savior doesn't prove His deity.",
    "Response: those human 'saviors' only delivered Israel from physical/political oppression — never from sin or unto eternal life, which Scripture reserves to God alone (Isaiah 43:10-11, Hosea 13:4).",
    "The NT applies distinctly divine-salvation language to Jesus: he saves 'his people from their sins' (Matt 1:21), redeems a people 'of his own' (Titus 2:13-14) — mirroring what only Yahweh does for Israel (Exod 19:5, Ezek 37:23).",
    "Revelation 7:10 even directs worship-language salvation ascriptions jointly 'to our God... and to the Lamb.'",
    "Key move: distinguish 'savior' as a mere title (used loosely of agents) from 'Savior' as a functional claim (forgiving sin, granting eternal life) — only the latter, applied to Jesus, entails deity.",
  ],
  "christian-theology/christological-issues/ot-appearances-of-christ-as-the-angel-of-god": [
    "The 'Angel of the LORD' in the OT is repeatedly identified as God himself, not a created angel (Gen 16:7-13, 22:11-16; Exod 3:2-6; Judg 6:11-24; 13:20-22; Zech 1:11-12, 3:1-6, 12:8).",
    "Evidence for deity: he forgives sin (Zech 3:4, a divine prerogative), accepts worship, speaks as 'the LORD' in the first person, and is called 'God' directly by those who encounter him (Hagar: 'the God who sees me').",
    "Yet he's also distinct FROM Yahweh in some texts (he speaks TO the LORD, Zech 1:12, 3:1-2) — an early OT glimpse of plurality-within-unity in God (a seed of Trinitarian doctrine).",
    "Evangelical scholarship (Enns, Lindsey, Feinberg) identifies this figure as the preincarnate Christ — noting the Angel of the LORD never appears again after the incarnation, since the Son now appears in the flesh instead.",
    "Strong, source-dense article for defending Christ's pre-existence and deity directly from the Hebrew Bible, independent of NT claims.",
  ],
  "christian-theology/theological-issues/is-gabriel-really-the-holy-spirit": [
    "Responds to a Muslim apologist's claim that the Quran identifies Gabriel and 'the Spirit' as the same entity, based on verses (2:97, 16:102, 26:193) about revelation being 'sent down.'",
    "Counters that the Quran itself uses the verbs for 'sending down' (nazzala) and 'casting' (alqa) interchangeably and in parallel constructions about angels, undermining the argument that different verbs must mean different agents.",
    "Q. 77:5's 'those who cast the Reminder' is shown, via classical tafsirs (Jalalayn, Ibn Abbas, Ibn Kathir), to refer to angels (plural) bringing revelation — implying multiple agents of revelation, not one single Spirit=Gabriel entity.",
    "Demonstrates that even mainstream classical Muslim exegesis doesn't uniformly support the one-agent reading modern apologists rely on.",
    "A technical, Arabic-grammar-level rebuttal — useful mainly for detailed one-on-one engagement with informed Muslim interlocutors rather than general apologetics.",
  ],
  "christian-theology/biblical-issues/does-the-holy-bible-claim-to-be-the-inspired-word-of-god": [
    "Objection: 2 Timothy 3:16 ('all Scripture is God-breathed') originally referred only to the OT, since NT books didn't exist yet when Paul wrote it — so it can't be used to claim NT inspiration.",
    "Response: Paul elsewhere explicitly quotes Luke's Gospel as 'Scripture' alongside Moses (1 Tim 5:18, quoting Luke 10:7 verbatim in Greek) — showing Gospel material was already treated as Scripture within the apostolic era.",
    "Paul repeatedly claims his own preaching and writing are Spirit-taught/God's word, not merely human wisdom (1 Cor 2:13; 2 Cor 13:3,10; Eph 3:1-5; 1 Thess 2:13) and commands his letters be read publicly in churches alongside Scripture (Col 4:16).",
    "The cumulative case: 'Scripture' status in the apostolic mind wasn't fixed to a closed OT canon — it extended dynamically to what God was producing through his apostles/associates in real time.",
    "Good reference article for Bible-inspiration objections generally, not just the Islamic angle — the internal NT self-testimony case applies broadly.",
  ],
  "christian-theology/polemical-issues/the-apostles-of-christ-messengers-of-god-or-mere-disciples": [
    "Surah 36:13-29 tells of three unnamed 'messengers' sent to Antioch; multiple major Islamic sources (Tafsir al-Jalalayn, Tanwir al-Miqbas/Ibn Abbas, al-Tabari, al-Suyuti, and even sources Ibn Kathir cites while disagreeing) identify these three as Peter, John, and Paul — sent as Jesus's apostles.",
    "Article's apologetic point: several authoritative, mainstream Islamic exegetical traditions themselves affirm the apostles functioned as divinely-sent 'messengers' on par with prophets — which Muslims can appeal to when trying to argue apostolic authority is a Quranic category too.",
    "Useful for turning a Quranic narrative into common ground: the Quran's own commentators treat Peter, Paul, and John as legitimate messengers of Christ's mission, which — turned back on the objector — implies the Quran itself doesn't uniformly deny apostolic derivative authority.",
    "This is a heavily source-quoted, comparative-religion-style article (long, dense with named classical Muslim scholars) — best used as a reference on what classical tafsir literature says about Surah 36:13, not a quick-read piece.",
    "Complements the Trinity/deity-of-Christ cluster by showing apostolic authority has some (contested) Quranic and tafsir-based grounding.",
  ],
  "christian-theology/general-issues/the-historicity-of-jonah-examined": [
    "Objection 1 (geographic/miracle 'error'): critics claim Jonah's fish supposedly vomited him at Nineveh, which is inland with no sea access — but the text (Jonah 2:10, 3:1-3) never says this; it says 'dry land,' and a second, later call from God sends him TO Nineveh afterward, implying he landed elsewhere (possibly near Tarshish/Spain per 1:3).",
    "Objection 2 (moral): critics call the OT's God unforgiving/genocidal for commanding conquest of Canaanite peoples.",
    "Response: Deuteronomy 9:4 and Leviticus 18 specify the conquered nations were judged for entrenched, specific abominations (incest, bestiality, child sacrifice to Molech) — this is framed as judicial punishment, not arbitrary ethnic violence.",
    "God is shown as patient before judgment — Genesis 15:12-16 shows a fixed, delayed timeline ('the sin of the Amorites has not yet reached its full measure') allowing generations for repentance before judgment falls.",
    "Core defensive pattern demonstrated: (1) check whether the text actually says what the objection claims before defending it, (2) reframe 'harsh OT judgment' passages within their stated moral/legal rationale rather than conceding they're arbitrary.",
  ],
  "christian-theology/church-history-and-denominations/the-reformation": [
    "The Reformation (16th c.) was the partial disruption of the Western Church that produced national/territorial Protestant churches, rejecting the Mass's sacrificial character and the pope's supremacy — but historians increasingly see it as much a political/economic revolt (against papal taxation, benefice abuses, and the Church's quasi-state power) as a purely theological one.",
    "The medieval Church functioned essentially as an international state with its own laws, courts, taxation (annates, tithes), and enforcement — a structure whose abuses (financial exploitation via indulgences, 'reservations' of benefices, papal claims to depose kings) built up resentment for centuries before Luther, especially in Germany.",
    "Trigger event: 1517 — Johann Tetzel's indulgence campaign (funding partly a corrupt deal letting Albert of Brandenburg hold multiple archbishoprics) provoked Luther's 95 Theses, challenging indulgences' theology of repentance vs. purchased pardon; Luther publicly burned papal decrees and canon law in 1520.",
    "Spread was uneven and shaped by politics as much as doctrine: north Germany, Scandinavia, England, Scotland, the Dutch Netherlands, parts of Switzerland broke from Rome; France, Italy, Spain, Poland, and the Habsburg lands remained (or returned to) Catholic; the Anabaptists formed a persecuted 'radical' wing rejecting both Catholic and mainline Protestant state-church models.",
    "Good reference for denominational literacy: explains WHY Lutheran/Calvinist/Anglican/Anabaptist splits look different from each other (state-aligned vs. separatist) rather than treating 'Protestant' as one undifferentiated block.",
  ],
  "christian-theology/short-summaries/jesus-christ-the-absolutely-and-essentially-good-god": [
    "Syllogism structure: (A) Scripture says only God is absolutely/essentially good and holy (Mark 10:17-18 — Jesus himself says 'no one is good except God alone'; Rev 15:4; Rom 3:9-13 — no human is righteous).",
    "(B) Scripture also calls Jesus absolutely holy/good — 'the Holy One of God' (Mark 1:23-24), sinless (John 8:29,46), 'the good shepherd' (John 10:11,14), 'the Holy and Righteous One' (Acts 3:13-15).",
    "(C) Therefore Jesus is God in the flesh — reinforced by direct deity texts: John 1:1-14 ('the Word was God... became flesh'), Thomas's confession 'My Lord and my God!' (John 20:28-29), Rom 9:5, Col 2:9-10, Titus 2:13-14, Heb 1:8-12.",
    "Turns the 'why did Jesus call the rich man's flattery into a denial of his own goodness?' objection (Mark 10:18) into a proof rather than a problem: it only works as a proof of deity if the reader independently knows Jesus WAS called good/holy elsewhere in exactly the absolute sense reserved for God.",
    "Good compact model for structuring a syllogistic apologetic argument — useful template for building similar 'good = God' style arguments on other divine attributes (omniscience, eternality, etc.).",
  ],
  "eastern-traditions/core-teachings/the-four-noble-truths": [
    "Buddhism's most basic teaching: suffering/stress (dukkha), its cause (craving/tanha), its cessation (nibbana), and the path to cessation (the Noble Eightfold Path) — framed as diagnosis-and-cure rather than pessimism.",
    "Truths are meant to be experienced/practiced, not merely believed — each has an assigned duty: suffering is to be comprehended, its cause abandoned, its cessation realized, the path developed.",
    "Rejects the Western 'me/not me, being/not being' framework entirely — replaces it with cause-and-effect, skillful-vs-unskillful categories, sidestepping metaphysical questions about the self.",
    "Central to interfaith comparison: unlike Christianity's sin-guilt-forgiveness framework rooted in relationship with a personal God, Buddhism frames the human problem as craving/attachment to be extinguished through self-effort and insight, with no need for a savior, atonement, or divine grace.",
  ],
  "eastern-traditions/meditation-and-mental-development/basic-breath-meditation-instructions": [
    "A practical breath-meditation script by Thanissaro Bhikkhu: begin by silently wishing yourself and then all beings well, since (per the text) you can't authentically wish others well without first being able to wish it for yourself.",
    "Explicitly framed as happiness-seeking that must look inward rather than to changeable external things — happiness is found only 'in the present.'",
    "Technique: settle attention on the breath at a comfortable spot in the body, then systematically move attention through body regions noticing/smoothing tension.",
    "Explicitly presented as religiously neutral ('the breath doesn't belong to Buddhism or Christianity') — worth noting when assessing whether Buddhist meditation techniques are separable from Buddhist metaphysics.",
    "Useful comparison point: purely self-directed, technique-based inner calm vs. the Christian practice of prayer as address to a personal God — structurally similar postures but fundamentally different objects/purposes.",
  ],
  "eastern-traditions/ethics-and-conduct/the-healing-power-of-the-precepts": [
    "Thanissaro Bhikkhu frames the Buddha as a doctor treating spiritual illness, and the Five Precepts as therapy for two 'wounds': regret (over failures) and denial (of the failure or of the standard itself).",
    "Argues the precepts work as mental-health tools because they are practical, clear-cut, humane, and 'worthy of respect' — contrasted with 'impossible standards' that damage self-esteem.",
    "Frames ethical living as fundamentally self-interested/therapeutic (builds self-respect via a track record of trustworthy behavior) rather than obligatory to a personal moral Lawgiver.",
    "Key contrast for apologetic use: Buddhist ethics ground moral standards in psychological health and karma (self-generated consequences), NOT in the character or command of a personal God.",
    "Precepts are tied to karma doctrine: 'the most important powers shaping your experience... are the intentional thoughts, words, and deeds you choose.'",
  ],
  "eastern-traditions/kamma-and-rebirth/kamma": [
    "A study guide to karma organized around Pali canon excerpts; explicitly rejects three 'non-Buddhist' deterministic theories: (1) all experience is caused by past action alone, (2) all experience is caused by a creator god's decree, (3) all experience is random/uncaused.",
    "Notably, the Buddha rejects theistic determinism on the same grounds as fatalism and randomness — all three, he argues, remove moral responsibility and effort.",
    "Key theological contrast for apologetics: this is a direct, explicit Buddhist rejection of a creator-God model of causation — important when comparing Buddhist karma to divine providence.",
    "Karma's mechanics: intention (cetana) is the essence of kamma; actions produce discernible, learnable patterns of result, and results can be immediate or delayed across lifetimes.",
    "Distinguishes 'mundane right view' (good karma leading to good rebirths) from 'transcendent right view' (karma leading to liberation) — helpful for not conflating popular 'karma = cosmic fairness' folk belief with canonical doctrine.",
  ],
  "eastern-traditions/not-self-and-liberation/no-self-or-not-self": [
    "Corrects a common Western misreading: the Buddha did NOT teach 'there is no self' as a metaphysical claim — when directly asked whether the self exists or not, he refused to answer either way, calling both extremes 'wrong view.'",
    "His stated reason: any answer to 'does the self exist' produces clinging (either to a self-concept or to its negation) and thus suffering — the question itself 'should be put aside,' not answered.",
    "Anatta (often mistranslated 'no-self') is better understood as a 'not-self' STRATEGY — a practical technique of examining experience and asking 'is this me/mine? if not, why cling to it?' — rather than a doctrinal assertion about ultimate reality.",
    "Explicitly notes the tension this creates with Judeo-Christian assumptions (an eternal soul) and even with Buddhist rebirth/karma doctrine itself (if there's no self, what takes rebirth?).",
    "Useful precision point: don't caricature Buddhism as flatly denying personal existence — the canonical position is agnostic/pragmatic on the metaphysics of selfhood, harder to refute head-on than a bare 'no self' claim.",
  ],
  "eastern-traditions/sutta-translations/dhammacakkappavattana-sutta": [
    "The Buddha's first sermon (to five monks at Sarnath) laying out the Middle Way between sensual indulgence and self-affliction, and formally stating the Four Noble Truths for the first time.",
    "States the truths in the canonical fourfold formula: stress exists; its origin is craving; its cessation is the fading of that craving; the path to cessation is the Noble Eightfold Path.",
    "The Buddha describes his enlightenment as requiring 'three rounds, twelve permutations' of insight into each truth before he could claim full awakening — awakening is systematic/exhaustive, not a single flash of insight.",
    "Kondañña becomes the first enlightened disciple upon hearing this sermon, prompting a cascade of celestial beings proclaiming that the 'Wheel of Dhamma' has been set in motion.",
    "Foundational text — analogous in weight to a Christian's Sermon on the Mount for understanding what Buddhists consider the very starting point of the entire tradition.",
  ],
  "eastern-traditions/monastic-life-and-the-sangha/vinaya-pitaka": [
    "The Vinaya Pitaka is the first of the three 'baskets' of the Pali Canon — the codified rules and etiquette governing monks and nuns, and the framework for how the monastic Sangha functions internally and with lay supporters.",
    "Rules arose reactively and case-by-case: whenever a monk acted badly, the Buddha issued a specific rule in response.",
    "The tradition's own framing: 'Dhamma-vinaya' (Doctrine and Discipline) is a single integrated whole — Vinaya isn't cultural baggage but is considered inseparable from and foundational to the Dhamma itself.",
    "Structured in three parts: Suttavibhanga (basic rules + origin stories), Khandhaka (etiquette/procedures), and Parivara (a recap/classification of the rules).",
    "Comparison point: unlike Christian ecclesiology (where church order is generally seen as secondary application of doctrine), Buddhism treats communal monastic discipline as co-equal and inseparable from doctrine.",
  ],
  "eastern-traditions/teachers-and-traditions/thai-forest-traditions": [
    "Surveys the lineage of the Thai Forest (Kammatthana) tradition founded by Ajaan Sao Kantasilo (1861-1941) and his student Ajaan Mun Bhuridatta (1870-1949), who established the wandering, meditation-focused forest-monk movement.",
    "Traces successive generations of teachers who each took up the wandering ascetic life under Ajaan Mun or his direct disciples, gradually establishing settled forest monasteries as they aged.",
    "Common biographical pattern: dissatisfaction with routine 'village temple' Buddhism, re-ordination in the stricter Dhammayut sect, and a period of wandering before eventually settling and attracting large followings.",
    "Primarily a reference/index article (short teacher bios with links) rather than a doctrinal argument — useful for background on modern Theravada monastic culture and lineage-based authority structures.",
    "Comparison point: authority in this tradition is transmitted through direct teacher-to-student lineage and personal charisma/attainment (a living guru model) rather than through a fixed canon interpreted by an institutional hierarchy.",
  ],
};
